# docker compose -f docker-compose-postgres.yaml up -d > logs/postgres.txt 

networks:
  shared_net:
    external: true


services:
 # docker exec -it postgres psql -U dockers -d dockers
 postgres:
  image: postgres:18.3
  pull_policy: missing
  container_name: postgres
  restart: always
  environment:
   POSTGRES_USER: dockers
   POSTGRES_PASSWORD: dockers
   POSTGRES_DB: dockers
  ports:
   - "5432:5432"
  volumes:
   - db-data:/var/lib/postgresql
  networks:
   - shared_net


volumes:
  db-data:
    driver: local
