#  1. Start postgres first: docker compose -f docker-compose-postgres.yaml up --force-recreate -d > logs/postgres.txt
#  2. Create the keycloak database: docker exec postgres psql -U dockers -c "CREATE DATABASE keycloak;"
#
# Start Keycloak:
#  docker compose -f docker-compose-keycloak.yaml up --force-recreate -d > logs/keycloak.txt
#
# Admin console: http://localhost:2305 (admin / admin)

# This makes sense to create it to get Access tokens that you can control: TTL to 1000 minutes (enough for a day).
# Tho achieve this:
# 1.) replace the temporary admin user (in master realm having the role "admin"),
# 2.) create a realm "tests",
# 3.) create a user,
# 4.) change the token TTL in realm settings to 1000 minutes.

networks:
  shared_net:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: dockers
      KC_DB_PASSWORD: dockers
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      # Debugging options for the theme.
      KC_SPI_THEME_CACHE_THEMES: false
      KC_SPI_THEME_CACHE_TEMPLATES: false
      KC_SPI_THEME_STATIC_MAX_AGE: -1
    ports:
      - "2305:8080"
    volumes:
      - ./src/keycloak-theme:/opt/keycloak/themes/platform
    networks:
    - shared_net